driver:
  name: vagrant
  require_chef_omnibus: latest
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
    run_list:
    - recipe[selinux::disabled]

suites:
  - name: hybris-standalone
    run_list:
    - recipe[hybris_test::standalone]
  - name: hybris-config
    run_list:
    - recipe[hybris_test::config]
